version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build \#$CODEBUILD_BUILD_NUMBER starting
      - mvn install
artifacts:
  files:
    - '**/*'
  name: release_1.0.$CODEBUILD_BUILD_NUMBER
